apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name}}-service
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{ .Values.common.name}}
  ports:
    - name: {{ .Values.common.port.name}}
      port: {{ .Values.common.port.value}}