spring:
  application:
    name: jokes-application
  jackson:
    default-property-inclusion: non_empty
    serialization:
      CLOSE_CLOSEABLE: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    time-zone: UTC
  web:
    resources:
      add-mappings: false
  main:
    cloud-platform: kubernetes
    log-startup-info: true
    web-application-type: servlet
    banner-mode: off

springdoc:
  webjars:
    prefix: /documentation/ui
  swagger-ui:
    path: /documentation
    disable-swagger-default-url: true
  api-docs:
    path: /documentation/api

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  forward-headers-strategy: framework

feign-client:
  chuck-norris.url: https://api.chucknorris.io